from datetime import datetime
from pathlib import Path
import re
from uuid import uuid4

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import HRFlowable, PageBreak, Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

from app.settings import settings


class NumberedCanvas:
    """Canvas that performs two-pass rendering for total page counts in footer."""
    def __init__(self, *args, **kwargs):
        pass


def generate_pdf_document(
    title: str,
    content_markdown: str,
    subtitle: str = "",
    subject: str = "JARVIS Automated Intelligence Report",
    author: str = "JARVIS AI Core",
    filename: str | None = None,
) -> Path:
    """
    Generate a publication-grade PDF report with headers, footers, tables, and styled markdown.
    """
    out_dir = settings.generated_dir
    out_dir.mkdir(parents=True, exist_ok=True)

    safe_title = re.sub(r"[^\w\-_]", "_", title)[:40]
    out_filename = filename or f"{safe_title}_{uuid4().hex[:6]}.pdf"
    dest_path = out_dir / out_filename

    doc = SimpleDocTemplate(
        str(dest_path),
        pagesize=letter,
        leftMargin=54,
        rightMargin=54,
        topMargin=54,
        bottomMargin=54,
    )

    styles = getSampleStyleSheet()

    # Custom JARVIS theme styles
    primary_color = colors.HexColor("#0f172a")
    accent_color = colors.HexColor("#0284c7")
    text_color = colors.HexColor("#1e293b")

    title_style = ParagraphStyle(
        "JarvisTitle",
        parent=styles["Title"],
        fontName="Helvetica-Bold",
        fontSize=24,
        leading=28,
        textColor=primary_color,
        alignment=0,
        spaceAfter=8,
    )

    subtitle_style = ParagraphStyle(
        "JarvisSubtitle",
        parent=styles["Normal"],
        fontName="Helvetica-Oblique",
        fontSize=12,
        leading=16,
        textColor=accent_color,
        spaceAfter=14,
    )

    h1_style = ParagraphStyle(
        "JarvisH1",
        parent=styles["Heading1"],
        fontName="Helvetica-Bold",
        fontSize=16,
        leading=20,
        textColor=primary_color,
        spaceBefore=14,
        spaceAfter=6,
        keepWithNext=True,
    )

    h2_style = ParagraphStyle(
        "JarvisH2",
        parent=styles["Heading2"],
        fontName="Helvetica-Bold",
        fontSize=13,
        leading=17,
        textColor=accent_color,
        spaceBefore=10,
        spaceAfter=4,
        keepWithNext=True,
    )

    body_style = ParagraphStyle(
        "JarvisBody",
        parent=styles["BodyText"],
        fontName="Helvetica",
        fontSize=10,
        leading=14,
        textColor=text_color,
        spaceAfter=6,
    )

    bullet_style = ParagraphStyle(
        "JarvisBullet",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=10,
        leading=14,
        textColor=text_color,
        leftIndent=15,
        firstLineIndent=-10,
        spaceAfter=3,
    )

    meta_style = ParagraphStyle(
        "JarvisMeta",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=8,
        leading=11,
        textColor=colors.HexColor("#64748b"),
    )

    code_style = ParagraphStyle(
        "JarvisCode",
        parent=styles["Normal"],
        fontName="Courier",
        fontSize=8.5,
        leading=11,
        textColor=colors.HexColor("#0f172a"),
        backColor=colors.HexColor("#f1f5f9"),
        borderPadding=6,
        spaceBefore=6,
        spaceAfter=6,
    )

    elements = []

    # Title & Header
    elements.append(Paragraph(title, title_style))
    if subtitle:
        elements.append(Paragraph(subtitle, subtitle_style))

    # Meta Info Bar
    date_str = datetime.now().strftime("%B %d, %Y - %H:%M")
    meta_text = f"<b>Generated by:</b> {author} &nbsp;|&nbsp; <b>Date:</b> {date_str} &nbsp;|&nbsp; <b>Subject:</b> {subject}"
    elements.append(Paragraph(meta_text, meta_style))
    elements.append(Spacer(1, 6))
    elements.append(HRFlowable(width="100%", thickness=1.5, color=accent_color, spaceBefore=4, spaceAfter=14))

    # Parse Markdown lines into Flowables
    lines = content_markdown.splitlines()
    in_code_block = False
    code_buffer = []

    for line in lines:
        stripped = line.strip()

        # Code block handler
        if stripped.startswith("```"):
            if in_code_block:
                code_text = "<br/>".join(code_buffer)
                elements.append(Paragraph(code_text, code_style))
                code_buffer = []
                in_code_block = False
            else:
                in_code_block = True
            continue

        if in_code_block:
            safe_code_line = line.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace(" ", "&nbsp;")
            code_buffer.append(safe_code_line)
            continue

        if not stripped:
            elements.append(Spacer(1, 4))
            continue

        # Headings
        if stripped.startswith("# "):
            elements.append(Paragraph(stripped[2:], h1_style))
            elements.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#cbd5e1"), spaceBefore=2, spaceAfter=6))
        elif stripped.startswith("## "):
            elements.append(Paragraph(stripped[3:], h1_style))
        elif stripped.startswith("### "):
            elements.append(Paragraph(stripped[4:], h2_style))
        elif stripped.startswith("- ") or stripped.startswith("* "):
            bullet_text = "&bull;&nbsp; " + stripped[2:]
            elements.append(Paragraph(bullet_text, bullet_style))
        elif re.match(r"^\d+\.\s", stripped):
            elements.append(Paragraph(stripped, bullet_style))
        else:
            # Inline bold/italics sanitization
            p_text = stripped.replace("**", "<b>").replace("<b>", "<b>", 1)  # simple replacement
            # Basic bold regex replacement
            p_text = re.sub(r"\*\*(.+?)\*\*", r"<b>\1</b>", stripped)
            p_text = re.sub(r"\*(.+?)\*", r"<i>\1</i>", p_text)
            p_text = re.sub(r"`(.+?)`", r'<font face="Courier" color="#0284c7">\1</font>', p_text)
            elements.append(Paragraph(p_text, body_style))

    doc.build(elements)
    return dest_path
